package au.com.marlo.trainning.service.orders;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.0.2
 * 2016-09-27T22:27:54.561-03:00
 * Generated source version: 3.0.2
 * 
 */
@WebService(targetNamespace = "http://www.marlo.com.au/trainning/service/Orders/", name = "Orders")
@XmlSeeAlso({au.com.marlo.trainning.xmltrainning.order.ObjectFactory.class, au.com.marlo.trainning.xmltrainning.product.ObjectFactory.class, au.com.marlo.trainning.xmltrainning.client.ObjectFactory.class, au.com.marlo.trainning.xmltrainning.request.ObjectFactory.class, au.com.marlo.trainning.xmltrainning.response.ObjectFactory.class, au.com.marlo.trainning.schema.order.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface Orders {

    @WebResult(name = "orderInquiryResponse", targetNamespace = "http://www.marlo.com.au/trainning/schema/Order", partName = "orderInquiryResponse")
    @WebMethod(operationName = "ProcessOrderPlacement", action = "http://www.marlo.com.au/trainning/service/Orders/ProcessOrderPlacement")
    public au.com.marlo.trainning.xmltrainning.response.Response processOrderPlacement(
        @WebParam(partName = "orderInquiry", name = "orderInquiry", targetNamespace = "http://www.marlo.com.au/trainning/schema/Order")
        au.com.marlo.trainning.xmltrainning.request.Request orderInquiry
    );
}
