//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.02 at 05:27:04 PM BRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.marlo.com.au/trainning/xmltrainning/order", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package au.com.marlo.trainning.xmltrainning.order;
