package au.com.supplier.persistence.dao;

import org.apache.log4j.Logger;

import au.com.supplier.persistence.model.OrderNumber;

/**
 * @author lteixeira
 * @param <Entity>
 */
public class OrderNumberGenerator extends DaoAbstract<OrderNumber> {
	private Logger log = Logger.getLogger(this.getClass());
	/**Return a new orderNumber generated by DB to Supplier.
	 * @return
	 * @throws Exception 
	 */
	public Long generateNewOrderNumber() throws Exception{
		log.info("PersistenceModule: generating an orderNumber");
		OrderNumber orderNumber = new OrderNumber();
		orderNumber =  super.persist(orderNumber);
		return orderNumber.getId();
	}
}
