drop schema if exists gbstoreds;
create schema gbstoreds;
use gbstoreds;

CREATE TABLE Entry (entryId BIGINT NOT NULL AUTO_INCREMENT, insertDate DATETIME, processDate DATETIME, PRIMARY KEY (entryId)) ENGINE = innodb;
CREATE TABLE Entry_StoreOrder (ENTRY_ENTRYID BIGINT, STOREORDERLIST_STOREORDERID BIGINT) ENGINE = innodb;
CREATE TABLE ItemStoreOrder (itemStoreOrderId BIGINT NOT NULL AUTO_INCREMENT, quantity BIGINT, PRODUCT_INTERNALID BIGINT, STOREORDER_STOREORDERID BIGINT, PRIMARY KEY (itemStoreOrderId)) ENGINE = innodb;
CREATE TABLE ItemSupplierOrder (itemSupplierOrderId BIGINT NOT NULL AUTO_INCREMENT, quantity BIGINT, PRODUCT_INTERNALID BIGINT, SUPPLIERORDER_SUPPLIERORDERID BIGINT, PRIMARY KEY (itemSupplierOrderId)) ENGINE = innodb;
CREATE TABLE Product (internalId BIGINT NOT NULL AUTO_INCREMENT, name VARCHAR(255), productSupplierId BIGINT, SUPPLIER_SUPPLIERID BIGINT, PRIMARY KEY (internalId)) ENGINE = innodb;
CREATE TABLE Store (storeId BIGINT NOT NULL AUTO_INCREMENT, name VARCHAR(255), PRIMARY KEY (storeId)) ENGINE = innodb;
CREATE TABLE StoreOrder (storeOrderId BIGINT NOT NULL AUTO_INCREMENT, insertDate DATETIME, status VARCHAR(255), updateDate DATETIME, STORE_STOREID BIGINT, PRIMARY KEY (storeOrderId)) ENGINE = innodb;
CREATE TABLE StoreOrder_ItemStoreOrder (STOREORDER_STOREORDERID BIGINT, ITEMSTOREORDERLIST_ITEMSTOREORDERID BIGINT) ENGINE = innodb;
CREATE TABLE Supplier (supplierId BIGINT NOT NULL AUTO_INCREMENT, name VARCHAR(255), PRIMARY KEY (supplierId)) ENGINE = innodb;
CREATE TABLE SupplierOrder (supplierOrderId BIGINT NOT NULL AUTO_INCREMENT, insertDate DATETIME, orderNumber VARCHAR(255), status VARCHAR(255), updateDate DATETIME, SUPPLIER_SUPPLIERID BIGINT, PRIMARY KEY (supplierOrderId)) ENGINE = innodb;
CREATE TABLE SupplierOrder_ItemSupplierOrder (SUPPLIERORDER_SUPPLIERORDERID BIGINT, ITEMSUPPLIERORDERLIST_ITEMSUPPLIERORDERID BIGINT) ENGINE = innodb;
CREATE TABLE SupplierOrder_StoreOrder (supplierOrderId BIGINT, storeOrderId BIGINT) ENGINE = innodb;
CREATE INDEX I_NTRYRDR_ELEMENT ON Entry_StoreOrder (STOREORDERLIST_STOREORDERID);
CREATE INDEX I_NTRYRDR_ENTRY_ENTRYID ON Entry_StoreOrder (ENTRY_ENTRYID);
CREATE INDEX I_TMSTRDR_PRODUCT ON ItemStoreOrder (PRODUCT_INTERNALID);
CREATE INDEX I_TMSTRDR_STOREORDER ON ItemStoreOrder (STOREORDER_STOREORDERID);
CREATE INDEX I_TMSPRDR_PRODUCT ON ItemSupplierOrder (PRODUCT_INTERNALID);
CREATE INDEX I_TMSPRDR_SUPPLIERORDER ON ItemSupplierOrder (SUPPLIERORDER_SUPPLIERORDERID);
CREATE INDEX I_PRODUCT_SUPPLIER ON Product (SUPPLIER_SUPPLIERID);
CREATE INDEX I_STRORDR_STORE ON StoreOrder (STORE_STOREID);
CREATE INDEX I_STRRRDR_ELEMENT ON StoreOrder_ItemStoreOrder (ITEMSTOREORDERLIST_ITEMSTOREORDERID);
CREATE INDEX I_STRRRDR_STOREORDER_STOREORDERID ON StoreOrder_ItemStoreOrder (STOREORDER_STOREORDERID);
CREATE INDEX I_SPPLRDR_SUPPLIER ON SupplierOrder (SUPPLIER_SUPPLIERID);
CREATE INDEX I_SPPLRDR_ELEMENT ON SupplierOrder_ItemSupplierOrder (ITEMSUPPLIERORDERLIST_ITEMSUPPLIERORDERID);
CREATE INDEX I_SPPLRDR_SUPPLIERORDER_SUPPLIERORDERID ON SupplierOrder_ItemSupplierOrder (SUPPLIERORDER_SUPPLIERORDERID);
CREATE INDEX I_SPPLRDR_ELEMENT1 ON SupplierOrder_StoreOrder (storeOrderId);
CREATE INDEX I_SPPLRDR_SUPPLIERORDERID ON SupplierOrder_StoreOrder (supplierOrderId);
CREATE TABLE OrderNumber (
  id bigint(20) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (id)
) ENGINE=InnoDB;



INSERT INTO gbstoreds.Product (name, productSupplierId, SUPPLIER_SUPPLIERID) VALUES ('Budweiser', 1, 1);
INSERT INTO gbstoreds.Product (name, productSupplierId, SUPPLIER_SUPPLIERID) VALUES ('Amstel', 2 , 2);
INSERT INTO gbstoreds.Product (name, productSupplierId, SUPPLIER_SUPPLIERID) VALUES ('Leffe', 3, 3);
INSERT INTO gbstoreds.Product (name, productSupplierId, SUPPLIER_SUPPLIERID) VALUES ('HoccusPoccus', 4, 1);
INSERT INTO gbstoreds.Product (name, productSupplierId, SUPPLIER_SUPPLIERID) VALUES ('Heineken', 5, 1);

INSERT INTO gbstoreds.Store (name) VALUES ('Boteco da Esquina');
INSERT INTO gbstoreds.Store (name) VALUES ('Devassa');
INSERT INTO gbstoreds.Store (name) VALUES ('Bar da Marlo');

INSERT INTO gbstoreds.Supplier(name) VALUES ('SupplierA');
INSERT INTO gbstoreds.Supplier (name) VALUES ('SupplierB');
INSERT INTO gbstoreds.Supplier (name) VALUES ('SupplierC');
